var wrapper = document.createElement('div');
wrapper.classList.add('wrapper');
wrapper.style.border = '1px solid black';
wrapper.style.width = '1250px';
wrapper.style.height = '900px';
var b = document.getElementsByTagName('body');
document.body.appendChild(wrapper);
var p = document.createElement('p');
wrapper.appendChild(p);
p.innerHTML = 'Тест по программированию';
p.style.textAlign = 'center';
p.style.fontFamily = 'Arial';
p.style.fontSize = '20px';
var ol = document.createElement('ol');
wrapper.appendChild(ol);
var li1 = document.createElement('li');
ol.appendChild(li1);
li1.innerHTML = 'Вопрос №1';
li1.style.fontFamily = 'Arial';
li1.style.fontSize = '20px';
var input1 = document.createElement('input');
ol.appendChild(input1);
input1.type = 'checkbox';
input1.name = 'input1';
input1.style.marginTop = '10px';
input1.style.marginBottom = '8px';
   var label1 = document.createElement('label');
   ol.appendChild(label1);
   label1.innerHTML = 'Вариант ответа №1';
   label1.style.fontFamily = 'Arial';
   label1.style.fontSize = '17px';
   label1.style.fontWeight = 'bold';
var br1 = document.createElement('br');
ol.appendChild(br1);
var input2 = document.createElement('input');
ol.appendChild(input2);
input2.type = 'checkbox';
input2.name = 'input1';
input2.style.marginBottom = '8px';
   var label2 = document.createElement('label');
   ol.appendChild(label2);
   label2.innerHTML = 'Вариант ответа №2';
   label2.style.fontFamily = 'Arial';
   label2.style.fontSize = '17px';
   label2.style.fontWeight = 'bold';
var br2 = document.createElement('br');
ol.appendChild(br2);
var input3 = document.createElement('input');
ol.appendChild(input3);
input3.type = 'checkbox';
input3.name = 'input1';
input3.style.marginBottom = '15px';
   var label3 = document.createElement('label');
   ol.appendChild(label3);
   label3.innerHTML = 'Вариант ответа №3';
   label3.style.fontFamily = 'Arial';
   label3.style.fontSize = '17px';
   label3.style.fontWeight = 'bold';
var br3 = document.createElement('br');
ol.appendChild(br3);
var li2 = document.createElement('li');
ol.appendChild(li2);
li2.innerHTML = 'Вопрос №2';
li2.style.fontFamily = 'Arial';
li2.style.fontSize = '20px';
var input4 = document.createElement('input');
ol.appendChild(input4);
input4.type = 'checkbox';
input4.name = 'input2';
input4.style.marginTop = '10px';
input4.style.marginBottom = '8px';
   var label1 = document.createElement('label');
   ol.appendChild(label1);
   label1.innerHTML = 'Вариант ответа №1';
   label1.style.fontFamily = 'Arial';
   label1.style.fontSize = '17px';
   label1.style.fontWeight = 'bold';
var br4 = document.createElement('br');
ol.appendChild(br4);
var input5 = document.createElement('input');
ol.appendChild(input5);
input5.type = 'checkbox';
input5.name = 'input2';
input5.style.marginBottom = '8px';
   var label2 = document.createElement('label');
   ol.appendChild(label2);
   label2.innerHTML = 'Вариант ответа №2';
   label2.style.fontFamily = 'Arial';
   label2.style.fontSize = '17px';
   label2.style.fontWeight = 'bold';
var br5 = document.createElement('br');
ol.appendChild(br5);
var input6 = document.createElement('input');
ol.appendChild(input6);
input6.type = 'checkbox';
input6.name = 'input2';
input6.style.marginBottom = '15px';
   var label3 = document.createElement('label');
   ol.appendChild(label3);
   label3.innerHTML = 'Вариант ответа №3';
   label3.style.fontFamily = 'Arial';
   label3.style.fontSize = '17px';
   label3.style.fontWeight = 'bold';
var br6 = document.createElement('br');
ol.appendChild(br6);
var li3 = document.createElement('li');
ol.appendChild(li3);
li3.innerHTML = 'Вопрос №3';
li3.style.fontFamily = 'Arial';
li3.style.fontSize = '20px';
var input7 = document.createElement('input');
ol.appendChild(input7);
input7.type = 'checkbox';
input7.name = 'input3';
input7.style.marginTop = '10px';
input7.style.marginBottom = '8px';
   var label1 = document.createElement('label');
   ol.appendChild(label1);
   label1.innerHTML = 'Вариант ответа №1';
   label1.style.fontFamily = 'Arial';
   label1.style.fontSize = '17px';
   label1.style.fontWeight = 'bold';
var br7 = document.createElement('br');
ol.appendChild(br7);
var input8 = document.createElement('input');
ol.appendChild(input8);
input8.type = 'checkbox';
input8.name = 'input3';
input8.style.marginBottom = '8px';
   var label2 = document.createElement('label');
   ol.appendChild(label2);
   label2.innerHTML = 'Вариант ответа №2';
   label2.style.fontFamily = 'Arial';
   label2.style.fontSize = '17px';
   label2.style.fontWeight = 'bold';
var br8 = document.createElement('br');
ol.appendChild(br8);
var input9 = document.createElement('input');
ol.appendChild(input9);
input9.type = 'checkbox';
input9.name = 'input3';
   var label3 = document.createElement('label');
   ol.appendChild(label3);
   label3.innerHTML = 'Вариант ответа №3';
   label3.style.fontFamily = 'Arial';
   label3.style.fontSize = '17px';
   label3.style.fontWeight = 'bold';
var br9 = document.createElement('br');
ol.appendChild(br9);
var button = document.createElement('button');
wrapper.appendChild(button);
button.innerHTML = 'Проверить мои результаты';
button.fontFamily = 'Arial';
button.style.fontSize = '20px';
button.style.marginLeft = '470px';
button.style.marginTop = '30px';
button.style.width = '327px';
button.style.height = '53px';
button.style.backgroundColor = '#cfe2f3';
button.style.border = '2px solid black';